### ISSUE TITLE
RM - add/edit RM 

### ISSUE THREAD

**Issue by ilyashussain143** [mamillapalli/OAAdmin#128]
RM - add multiple customer , it's showing one customer only 
![image](https://user-images.githubusercontent.com/9261827/145165793-77c099ac-e5e7-47de-be05-be34006d0361.png)

**Comment by mamillapalli** [comment]
as the other cutomerid "Andhra bank" is a bank (not customer) , it only added "Ravikanth3" , rm's can be added to only customers not banks, try adding other than banks, it should work
