### ISSUE TITLE
Get Agreement exception is occurring 

### ISSUE THREAD

**Issue by ilyashussain143** [mamillapalli/OAAdmin#174]
{
    "timestamp": "2021-12-23T16:07:32.091+00:00",
    "message": "Null value was assigned to a property [class org.trishanku.oa.admin.entity.Agreement.anchorPartyApprovalRequired] of primitive type setter of org.trishanku.oa.admin.entity.Agreement.anchorPartyApprovalRequired; nested exception is org.hibernate.PropertyAccessException: Null value was assigned to a property [class org.trishanku.oa.admin.entity.Agreement.anchorPartyApprovalRequired] of primitive type setter of org.trishanku.oa.admin.entity.Agreement.anchorPartyApprovalRequired",
    "details": "uri=/api/v1/agreements"
}

**Comment by mamillapalli** [comment]
data issue , please try with the latest docker images
