### ISSUE TITLE
Edit SBR is not working 

### ISSUE THREAD

**Issue by ilyashussain143** [mamillapalli/OAAdmin#175]
{
    "timestamp": "2021-12-23T16:11:11.808+00:00",
    "message": "No value present",
    "details": "uri=/api/v1/sbrs"
}

![image](https://user-images.githubusercontent.com/9261827/147266066-fa44be65-7eaa-4ce2-a6c1-f91362e3d51b.png)

**Comment by mamillapalli** [comment]
check the error.log and see the value that should be there as part of the request and add it, if still issue persists, can check
