### ISSUE TITLE
Get super Admin , is not getting record , always showing one record 

### ISSUE THREAD

**Issue by ilyashussain143** [mamillapalli/OAAdmin#193]
![image](https://user-images.githubusercontent.com/9261827/147977431-c627fd66-50f2-4534-bd11-4650f4b0bd43.png)

![image](https://user-images.githubusercontent.com/9261827/147977496-71dbb835-d47c-487d-a586-7a9f312d7841.png)

**Comment by mamillapalli** [comment]
add the super admin , with status true and you should see the record with doing get super admins

![image](https://user-images.githubusercontent.com/31787575/148421286-cf5044f6-b736-47a5-8840-dbf0ff5cc360.png)
